-- Inserir alguns pacientes de exemplo para teste
INSERT INTO patients (id, doctor_id, name, email, phone, city, state, birth_date, gender, cpf, address, emergency_contact, emergency_phone, medical_history, allergies, current_medications, status) VALUES 
(
    uuid_generate_v4(),
    'test-doctor-id',
    'Maria Silva Santos',
    'maria.silva@email.com',
    '(11) 99999-1234',
    'São Paulo',
    'SP',
    '1985-03-15',
    'F',
    '123.456.789-01',
    'Rua das Flores, 123, Centro',
    'João Silva',
    '(11) 99999-5678',
    'Hipertensão arterial, diabetes tipo 2',
    'Penicilina, dipirona',
    'Metformina 500mg, Losartana 50mg',
    'active'
),
(
    uuid_generate_v4(),
    'test-doctor-id',
    'João Pedro Oliveira',
    'joao.oliveira@email.com',
    '(11) 88888-9876',
    'São Paulo',
    'SP',
    '1978-07-22',
    'M',
    '987.654.321-02',
    'Av. Paulista, 1000, Bela Vista',
    'Ana Oliveira',
    '(11) 88888-5432',
    'Asma, rinite alérgica',
    'Aspirina',
    'Salbutamol, Loratadina',
    'active'
),
(
    uuid_generate_v4(),
    'test-doctor-id',
    'Ana Carolina Costa',
    'ana.costa@email.com',
    '(11) 77777-5555',
    'Rio de Janeiro',
    'RJ',
    '1992-11-08',
    'F',
    '456.789.123-03',
    'Rua Copacabana, 456, Copacabana',
    'Carlos Costa',
    '(11) 77777-1111',
    'Depressão, ansiedade',
    'Nenhuma conhecida',
    'Sertralina 50mg',
    'active'
)
ON CONFLICT (id) DO NOTHING;
