# Cloud Build pipeline to build and deploy the backend (Gateway) to Cloud Run
# Uses the monorepo Dockerfile at configs/docker/gateway.Dockerfile

# Substitutions you can override in the trigger or with: gcloud builds submit --substitutions=...
# _SERVICE: Cloud Run service name
# _REGION:  Cloud Run/Artifact Registry region (e.g. us-central1, southamerica-east1)
# _REPO:    Artifact Registry Docker repository name (must exist)
# _DOCKERFILE: Path to the Dockerfile to build
substitutions:
  _SERVICE: "medcall-gateway"
  _REGION: "southamerica-east1"
  _REPO: "medcall"
  _DOCKERFILE: "configs/docker/gateway.Dockerfile"

# Produce and push an image like: REGION-docker.pkg.dev/PROJECT/REPO/SERVICE:SHORT_SHA
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"


options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # Create Artifact Registry repository if it doesn't exist
  - id: "create artifact registry repo"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts repositories describe ${_REPO} --location=${_REGION} || \
        gcloud artifacts repositories create ${_REPO} --repository-format=docker --location=${_REGION} --description="MedCall HomologDocker images"

  # Configure gcloud to use Artifact Registry Docker auth
  - id: "auth to artifact registry"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud --quiet auth configure-docker ${_REGION}-docker.pkg.dev

  # Build Docker image using the monorepo Dockerfile
  - id: "docker build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--file=${_DOCKERFILE}"
      - "--tag=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"
      - "."

  # Push the image to Artifact Registry
  - id: "docker push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"

  # Deploy to Cloud Run
  # IMPORTANTE: Configure as variáveis sensíveis diretamente no Console do Cloud Run
  - id: "deploy cloud run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--port=8080"
      - "--allow-unauthenticated"
      - "--cpu=1"
      - "--memory=1Gi"
      - "--max-instances=10"
      - "--concurrency=80"
      - "--timeout=300"
      - "--clear-secrets"
      - "--set-env-vars=NODE_ENV=production"
EKIT_API_SECRET:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,JWT_SECRET=JWT_SECRET:latest"

# Example build command (from repo root):
# gcloud builds submit --region=${_REGION} --config=cloudbuild.yaml \
#   --substitutions=_SERVICE=medcall-gateway,_REGION=us-central1,_REPO=medcall
